name: Project Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get -y install antlr4
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate ANTLR files
        working-directory: project/my_language
        run: antlr4 -Dlanguage=Python3 Grammar.g4 -visitor -o dist
      - name: Tests
        run: python ./scripts/run_tests.py
